[package.build.backend]
name = "pixi-build-rattler-build"
version = ">=0.4.0,<0.5.0"
channels = ["https://prefix.dev/pixi-build-backends", "conda-forge"]

[package.build.config]
experimental = true

[package.host-dependencies]
kimnara = { workspace = true }

[package.run-dependencies]
kimnara = { workspace = true }
